{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "newmind-ai.configMapName" . }}
  labels:
    {{- include "newmind-ai.labels" . | nindent 4 }}
data:
  # Application configuration
  app.yaml: |
    app:
      name: {{ .Values.app.name }}
      version: {{ .Values.app.version }}
      log_level: {{ .Values.env.LOG_LEVEL | default "INFO" }}
    
    kafka:
      bootstrap_servers: {{ .Values.env.KAFKA_BOOTSTRAP_SERVERS }}
      topic: {{ .Values.env.KAFKA_TOPIC }}
      group_id: {{ .Values.env.KAFKA_GROUP_ID }}
    
    qdrant:
      host: {{ .Values.env.QDRANT_HOST }}
      port: {{ .Values.env.QDRANT_PORT }}
      collection_name: {{ .Values.env.QDRANT_COLLECTION_NAME }}
    
    monitoring:
      metrics_port: {{ .Values.env.METRICS_PORT | default "9090" }}
      health_check_port: {{ .Values.env.HEALTH_CHECK_PORT | default "8080" }}
  
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}