apiVersion: v1
kind: Service
metadata:
  name: {{ include "newmind-ai.fullname" . }}
  labels:
    {{- include "newmind-ai.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.env.METRICS_PORT | default 9090 }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.env.HEALTH_CHECK_PORT | default 8080 }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "newmind-ai.selectorLabels" . | nindent 4 }}