groups:
  - name: newmind-ai-critical
    rules:
      - alert: SystemDown
        expr: up{job="newmind-ai"} == 0
        for: 1m
        labels:
          severity: critical
          service: newmind-ai
        annotations:
          summary: "NewMind AI sistemi çalışmıyor"
          description: "NewMind AI sistemi {{ $labels.instance }} üzerinde 1 dakikadan fazla süredir çalışmıyor."

      - alert: KafkaConnectionDown
        expr: kafka_connection_status == 0
        for: 2m
        labels:
          severity: critical
          service: kafka
        annotations:
          summary: "Kafka bağlantısı kesildi"
          description: "Kafka bağlantısı {{ $labels.instance }} üzerinde 2 dakikadan fazla süredir kesik."

      - alert: QdrantConnectionDown
        expr: qdrant_connection_status == 0
        for: 2m
        labels:
          severity: critical
          service: qdrant
        annotations:
          summary: "Qdrant bağlantısı kesildi"
          description: "Qdrant bağlantısı {{ $labels.instance }} üzerinde 2 dakikadan fazla süredir kesik."

      - alert: CircuitBreakerOpen
        expr: circuit_breaker_state == 1
        for: 1m
        labels:
          severity: critical
          service: "{{ $labels.service }}"
        annotations:
          summary: "Circuit breaker açık durumda"
          description: "{{ $labels.service }} servisi için circuit breaker 1 dakikadan fazla süredir açık durumda."

  - name: newmind-ai-performance
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Yüksek CPU kullanımı"
          description: "{{ $labels.instance }} üzerinde CPU kullanımı %80'in üzerinde (mevcut: {{ $value }}%)."

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Yüksek bellek kullanımı"
          description: "{{ $labels.instance }} üzerinde bellek kullanımı %85'in üzerinde (mevcut: {{ $value }}%)."

      - alert: HighDiskUsage
        expr: 100 - ((node_filesystem_avail_bytes{mountpoint="/"} * 100) / node_filesystem_size_bytes{mountpoint="/"}) > 90
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Yüksek disk kullanımı"
          description: "{{ $labels.instance }} üzerinde disk kullanımı %90'ın üzerinde (mevcut: {{ $value }}%)."

      - alert: SlowProcessingTime
        expr: avg(rate(processing_duration_seconds_sum[5m]) / rate(processing_duration_seconds_count[5m])) > 5
        for: 3m
        labels:
          severity: warning
          service: processing
        annotations:
          summary: "Yavaş işlem süresi"
          description: "Ortalama işlem süresi 5 saniyenin üzerinde (mevcut: {{ $value }}s)."

      - alert: LowSuccessRate
        expr: (sum(rate(processed_messages_total{status="success"}[5m])) / sum(rate(processed_messages_total[5m]))) * 100 < 95
        for: 5m
        labels:
          severity: warning
          service: processing
        annotations:
          summary: "Düşük başarı oranı"
          description: "Mesaj işleme başarı oranı %95'in altında (mevcut: {{ $value }}%)."

  - name: newmind-ai-errors
    rules:
      - alert: HighErrorRate
        expr: rate(error_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
          service: "{{ $labels.service }}"
        annotations:
          summary: "Yüksek hata oranı"
          description: "{{ $labels.service }} servisinde hata oranı dakikada 10'un üzerinde (mevcut: {{ $value }}/min)."

      - alert: DLQMessagesAccumulating
        expr: increase(dlq_messages_total[10m]) > 50
        for: 5m
        labels:
          severity: warning
          service: dlq
        annotations:
          summary: "DLQ'da mesaj birikimi"
          description: "Dead Letter Queue'da son 10 dakikada 50'den fazla mesaj birikti (mevcut: {{ $value }})."

      - alert: KafkaConsumerLag
        expr: kafka_consumer_lag > 1000
        for: 3m
        labels:
          severity: warning
          service: kafka
        annotations:
          summary: "Kafka consumer lag yüksek"
          description: "Kafka consumer lag 1000'in üzerinde (mevcut: {{ $value }})."

      - alert: QdrantSlowResponse
        expr: histogram_quantile(0.95, rate(qdrant_operations_duration_seconds_bucket[5m])) > 2
        for: 3m
        labels:
          severity: warning
          service: qdrant
        annotations:
          summary: "Qdrant yavaş yanıt süresi"
          description: "Qdrant operasyonlarının %95'i 2 saniyeden uzun sürüyor (mevcut: {{ $value }}s)."

  - name: newmind-ai-business
    rules:
      - alert: LowEmbeddingThroughput
        expr: rate(embedding_operations_total[5m]) < 1
        for: 10m
        labels:
          severity: warning
          service: embedding
        annotations:
          summary: "Düşük embedding throughput"
          description: "Embedding işlem oranı dakikada 1'in altında (mevcut: {{ $value }}/min)."

      - alert: NoMessageProcessing
        expr: rate(processed_messages_total[5m]) == 0
        for: 5m
        labels:
          severity: critical
          service: processing
        annotations:
          summary: "Mesaj işleme durdu"
          description: "Son 5 dakikada hiç mesaj işlenmedi."

      - alert: EmbeddingQualityDegraded
        expr: avg(embedding_quality_score) < 0.8
        for: 10m
        labels:
          severity: warning
          service: embedding
        annotations:
          summary: "Embedding kalitesi düştü"
          description: "Ortalama embedding kalite skoru 0.8'in altında (mevcut: {{ $value }})."

  - name: newmind-ai-infrastructure
    rules:
      - alert: PodRestartLoop
        expr: increase(kube_pod_container_status_restarts_total[1h]) > 5
        for: 5m
        labels:
          severity: warning
          service: kubernetes
        annotations:
          summary: "Pod sürekli yeniden başlıyor"
          description: "{{ $labels.pod }} pod'u son 1 saatte 5'ten fazla kez yeniden başladı."

      - alert: PersistentVolumeSpaceLow
        expr: (kubelet_volume_stats_available_bytes / kubelet_volume_stats_capacity_bytes) * 100 < 10
        for: 5m
        labels:
          severity: critical
          service: storage
        annotations:
          summary: "Persistent volume alanı az"
          description: "{{ $labels.persistentvolumeclaim }} volume'ünde %10'dan az alan kaldı."

      - alert: NodeNotReady
        expr: kube_node_status_condition{condition="Ready",status="true"} == 0
        for: 2m
        labels:
          severity: critical
          service: kubernetes
        annotations:
          summary: "Kubernetes node hazır değil"
          description: "{{ $labels.node }} node'u 2 dakikadan fazla süredir hazır değil."

      - alert: NetworkLatencyHigh
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
          service: network
        annotations:
          summary: "Yüksek network latency"
          description: "HTTP isteklerinin %95'i 1 saniyeden uzun sürüyor (mevcut: {{ $value }}s)."